# Generated by Django 3.2.6 on 2021-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_remove_product_img4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.FileField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.FileField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainimg',
            field=models.FileField(upload_to='pictures/'),
        ),
    ]
