# Generated by Django 3.2.6 on 2021-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_product_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellername',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
